language: java

mvn install -DskipTests=true

notifications:
  email:
    - byronlai@yahoo.com
    
jdk:
  - openjdk7
  
  before_script: 
  - echo TRAVIS_BUILD_NUMBER= $TRAVIS_BUILD_NUMBER
  - echo BUILD_INFO= $BUILD_INFO
  - echo DEPL_ENV= $DEPL_ENV