#%RAML 0.8
---
title: CIP-UAC
baseUri: http://localhost:8081/api/UserAccessControl

/Refresh:
  get:
    description: Refresh table from MySQL to Hadoop
#    queryParameters:
#      Tables:
#        displayName: Tables from MySQL
#        description: Comma separated list of tables of MySQL to refresh
#        example: country,cipmeasurecategory